[package]
name = "sl"
version = "6.0.0"
edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
crossterm = "0.28.1"
libc = "0.2.168"
signal-hook = "0.3.17"
widestring = "1.1.0"

[build-dependencies]
cmake = "0.1.52"
