.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH sl 1  "sl 6.0.1" 
.SH NAME
sl \- sl cures your bad habit of mistyping
.SH SYNOPSIS
\fBsl\fR [\fB\-a\fR|\fB\-\-accident\fR] [\fB\-l\fR|\fB\-\-logo\fR] [\fB\-F\fR|\fB\-\-fly\fR] [\fB\-c\fR|\fB\-\-c51\fR] [\fB\-f\fR|\fB\-\-files\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
sl is a highly advanced animation program for curing your bad habit of mistyping.
.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-accident\fR
An accident is occurring. People cry for help. Lists all files
.TP
\fB\-l\fR, \fB\-\-logo\fR
Little version
.TP
\fB\-F\fR, \fB\-\-fly\fR
It flies like the galaxy express 999
.TP
\fB\-c\fR, \fB\-\-c51\fR
C51 appears instead of D51
.TP
\fB\-f\fR, \fB\-\-files\fR
Disables listing files and directories
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v6.0.1
.SH AUTHORS
Toyoda Masashi (mtoyoda@acm.org)
