name: Posix Build SL
on:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install zig
        run: |
          if [ -f /home/linuxbrew/.linuxbrew/bin/brew ]; then
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          fi
          brew install zig

      - name: Build Debug
        run: |
          if [ -f /home/linuxbrew/.linuxbrew/bin/brew ]; then
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          fi
          cargo build

      - name: Build Release
        run: |
          if [ -f /home/linuxbrew/.linuxbrew/bin/brew ]; then
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          fi
          cargo build --release

      - name: Test
        run: |
          ./target/debug/sl -h
          ./target/debug/sl -V
          ./target/release/sl -h
          ./target/release/sl -V
