name: Windows Build SL

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [aarch64, x86_64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        run: rustup target install ${{ matrix.target }}-pc-windows-msvc

      - name: Install VCPKG
        run: cargo install cargo-vcpkg

      - name: Install vcpkg dependencies
        run: |
          $env:VCPKGRS_DYNAMIC="1"
          $env:VCPKG_ROOT="$env:VCPKG_INSTALLATION_ROOT"
          cargo vcpkg build --target=${{ matrix.target }}-pc-windows-msvc

      - name: Build Debug
        run: |
          $env:VCPKGRS_DYNAMIC="1"
          $env:VCPKG_ROOT="$env:VCPKG_INSTALLATION_ROOT"
          cargo build --target=${{ matrix.target }}-pc-windows-msvc

      - name: Build Release
        run: |
          $env:VCPKGRS_DYNAMIC="1"
          $env:VCPKG_ROOT="$env:VCPKG_INSTALLATION_ROOT"
          cargo build --target=${{ matrix.target }}-pc-windows-msvc --release

      - name: List Files
        shell: bash
        run: |
          ls -R target

      - name: Build Installer
        working-directory: ${{github.workspace}}/target
        run: |
          cmake .. -DARCH="${{ matrix.target }}"
          cpack -C Release

      - name: Rename Installer for ARM64
        if: matrix.target == 'ARM64'
        working-directory: ${{github.workspace}}/target
        shell: bash
        run: |
          INSTALLER=$(ls sl-*.exe)
          NEW_INSTALLER=$(echo $INSTALLER | sed 's/win64/woa64/')
          mv $INSTALLER $NEW_INSTALLER

      - name: Find Installer
        id: installer
        working-directory: ${{github.workspace}}/target
        shell: bash
        run: |
          INSTALLER=$(ls sl-*.exe)
          echo "installer=${INSTALLER}" >> $GITHUB_OUTPUT

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.installer.outputs.installer }}
          path: target/${{ steps.installer.outputs.installer }}
